### ISSUE TITLE
По дефолту билдить css для ie9

### ISSUE THREAD

**Issue by alexHlebnikov** [artem-malko/tars#29]
Сейчас при gulp build создается css только для нормальных браузеров. 
Так как ie9 пользуется ~~и любит~~ все еще большое количество людей, кажется правильным по умолчанию создавать css и для него.

**Comment by artem-malko** [comment]
Сделаю, чтобы таск для ie9 запускался автоматом, если есть хотя бы один файл со стилями для этого браузера.

**Comment by artem-malko** [comment]
Алгоритм работы будет такой:
1) Перед запуском проверяем, есть ли стили для ie9 отдельные.
2) Если есть, то добавляем их обработку.
3) Если нет, то ничего не делаем с ie9.

Во время работы сборщика в режиме dev не следим за созданием файлов для ie9, так как на ходу проблематично переключать режим работы.

Это облегчит работу?

**Comment by alexHlebnikov** [comment]
Да, кажется то, что нужно

**Comment by artem-malko** [comment]
Помещу в ближайший релиз.

**Comment by artem-malko** [comment]
Готово в версии version-1.2.0
Стили для IE9 собираются по умолчанию в любом случае. Используется копия основного потока файлов и один таск для основных стилей и стилей IE9.
